### PR TITLE
Add release and build workflows

### PR DESCRIPTION
**Pull request by jeanconn**
Add release and build workflows

### CODE REVIEW

**Comment by javierggt** [comment]
Is this a platform dependent package?

**Comment by jeanconn** [comment]
I only plan to run it on linux.  I don't know if there are bits that would work on the other systems.

**Comment by jeanconn** [comment]
So, do I remove the build-other block or cut down bits of it?

**Comment by javierggt** [comment]
No, you can leave it. It will not be tested, but still. I guess it is arch-dependent because of the entry-point.

**Review by javierggt — APPROVED** [review]
seems ok to me

**Pull request merged**
